# Generated by Django 5.2.8 on 2025-11-25 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('mini_truck', 'Mini Truck'), ('truck', 'Truck'), ('temp', 'Tempo')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('capacity_kg', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_electric', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('booking_type', models.CharField(choices=[('fast', 'Fast'), ('economy', 'Economy'), ('helper', 'With Helper')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_mins', models.IntegerField()),
                ('items_description', models.TextField()),
                ('is_green_fleet', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.vehicle')),
            ],
        ),
    ]
