# Generated by Django 5.2.8 on 2025-11-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='bookings.booking')),
            ],
            options={
                'db_table': 'tracking_logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['booking', 'timestamp'], name='tracking_lo_booking_14780e_idx')],
            },
        ),
    ]
